[package]
name = "compactor"
version = "0.1.0"
edition = "2024"
authors = ["Alex Sayers <alex@asayers.com>"]
license = "Unlicense"
repository = "https://github.com/asayers/compactor"

[dependencies]
jiff = "0.2.12"
linearize = { version = "0.1.4", features = ["derive"] }
